### PR TITLE
Fix exercises

### PR DESCRIPTION
**Pull request by hugojosefson**
This brings fixes to some of the exercises, which had either of:

* discrepancies between what the problem description said and the proposed solution did,
* unclear instructions regarding for example expected property names (which forced you to look at the solution to finish the task),
* grammar / typo mistakes in the problem description,
* or some other opportunity for improvement.

### CODE REVIEW

**Comment by mikaelbr** [comment]
Excellent! Thanks for your work! :tada:

**Comment by hugojosefson** [comment]
Great! Thanks for merging, and thanks for the excellent exercises :+1: 

If at all possible, it would be awesome if you would have time to publish the new version on npm today, because we will be using `bacon-love` tomorrow at Jayway for competence development. :)

**Comment by mikaelbr** [comment]
Sure! Published now

```shell
⇝ npm publish
+ bacon-love@1.2.1
```

**Comment by hugojosefson** [comment]
Perfect 👌 Thanks a lot!

**Pull request merged**
