### PR TITLE
ES2015 all the things?!

### PR DESCRIPTION
**Pull request by hugojosefson**
I suppose ES2015 for JavaScript code examples in general is inevitable. The question is rather that of timing; when is a good time to go all in with ES2015? When are people ready for seeing examples written this way?

Opening this pull request for discussion.

It updates all `problem.md`'s and `solution.js`'s to ES2015.

Note that Node.js >= 4.0.0 is required for actually using ES2015 when doing the exercises (because of Babel dependencies), and also for running `npm test` which runs the solutions.

### CODE REVIEW

**Comment by mikaelbr** [comment]
This is probably record time slow response for an issue. I'm really sorry about that. On the one hand I was unsure whether or not to include ES2015 things in this learning material, as it's not about that. But over the last 6 months I think a lot has changed and now more people than not (especially the ones this workshop is directed at) use many of the ES2015 features.

I'm still unsure if we should use `export` etc though, due to the discussions of module loader with node now. But I'm merging it and we can look into what's the best approach for this. Maybe we can also update this code to exclusively Node 6 now.

**Comment by mikaelbr** [comment]
I invited you as a collaborator to the project as this project doesn't get the attention it maybe should from me.

**Comment by hugojosefson** [comment]
Hi Mikael!

Hehe, I almost forgot about this PR. Good thing you revived it :)

Thanks for merging and adding me as collaborator. I have already added testing with Node 6 in Travis, and upgraded npm dependencies.

However, there seems to be an issue with my pushes on `mikaelbr/bacon-love` not triggering on your Travis account: https://travis-ci.org/mikaelbr/bacon-love . Compare to mine: https://travis-ci.org/hugojosefson/bacon-love . Maybe you can try removing the Travis-connection, and reenabling it? In case it hasn't picked up that I'm a collaborator...

On choosing which Node version we should require the user to have, I think it's okay to require them to use the latest LTS, which right now still is Node.js 4. IIRC, Node 6 will become LTS in October 2016.

**Comment by mikaelbr** [comment]
I don't see any pushes on this repo from you, only on your fork. But you can push directly to this repo and it should work 😄 

> On choosing which Node version we should require the user to have, I think it's okay to require them to use the latest LTS, which right now still is Node.js 4. IIRC, Node 6 will become LTS in October 2016.

That sounds good to me!

**Comment by mikaelbr** [comment]
Now it's triggering 👍

**Comment by hugojosefson** [comment]
Ah, yes, thanks. Apparently I had my git origin remote pointing in the wrong direction before :D

**Comment by mikaelbr** [comment]
I figured 😄

**Pull request merged**
